### PR TITLE
Update NNNN-concurrency-objc.md

### PR DESCRIPTION
**Pull request by benrimmington**
* Reduce horizontal scrolling.
* Fix errors and typos.

### CODE REVIEW

**Comment by benrimmington** [comment]
**FIXME:**

* The `generateCGImagesAsynchronously` API would need `__attribute__((swift_async(none)))`, because it calls `handler` for each `requestedTimes` element.

* Implementing only one of either
  `urlSession(_:dataTask:didReceive:completionHandler:)` or
  `urlSession(_:dataTask:didReceive:) async`
  wouldn't produce an error, because all `NSURLSessionDataDelegate` requirements are `@optional`.

**Comment by benrimmington** [comment]
Cc: @ktoso

**Review by DougGregor — APPROVED** [review]
Thank you!

**Comment by DougGregor** [comment]
I'm going to go ahead and merge this now, and we can tackle the FIXMEs in a follow-up. Thanks!

**Pull request merged**
